### ISSUE TITLE
Activity when user is about to reach his quota

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#105] opened 2014-07-07 14:20 UTC
Copied from todo in the code

**Comment by DeepDiver1975** [comment] 2015-05-12 08:29
already implemented via web_hooks - https://github.com/owncloud/web_hooks/wiki/Events-and-topics#event-quota

**Comment by felixboehm** [comment] 2015-09-24 13:04
@MTRichards

**Comment by nickvergessen** [comment] 2015-09-24 13:23
Should more be a notification?

**Comment by felixboehm** [comment] 2015-09-24 14:27
When a user has set a quota 
and his used disk space has reached 90% of the quota
then a notification should be sent to the users email address.

When a user has no quota set
and his used disk space has reached 90% of the remaining disk space
then a notification should be sent to the users email address.

Email should warn and contain infos about disk usage and quota.

As usual in the Activity app, you can set notification for Soft Quota to be in stream and / or email with checkboxes. Both options should be checked by default.

When a user has a quota of 0 Bytes, notification makes no sense.
0 Byte quota is often used to have "Guest Users" without own storage.

Does that make sense?

**Comment by karlitschek** [comment] 2015-09-24 14:47
@nickvergessen I think an activity and a notification

**Comment by MTRichards** [comment] 2015-09-24 16:44
@karlitschek and @nickvergessen Concur with Frank, the option for both makes sense to me - allow the user to pick the mechanism that works for them.

**Comment by MTRichards** [comment] 2015-11-19 21:41
Given this is backlog, is there opportunity for 9.0 here, or are we on to 9.1?

**Comment by MTRichards** [comment] 2016-01-15 16:00
@cmonteroluque @karlitschek is this 9.0 possible?

**Comment by nickvergessen** [comment] 2016-01-15 17:14
@MTRichards Few questions before a possible implementation can start:

* When the user was notified and ignores it, it should notify again after:
  + x uploads
  + x MB of uploads
  + x days
* When the user was notified, deleted stuff to be "good" again and uploads again, when should he be notified:
  + immediate
  + after x days
  + after x uploads
* Should the quota be checked on upload, of async (cron job, can potentially explode for many users)?

**Comment by cmonteroluque** [comment] 2016-01-15 20:46
adding @PVince81

**Comment by cmonteroluque** [comment] 2016-02-05 12:32
@MTRichards Joas is looking for guidance on questions above

**Comment by MTRichards** [comment] 2016-02-05 16:23
@cmonteroluque thanks for the ping.

> When the user was notified and ignores it, it should notify again after:

25% of the remaining quota is used.

>When the user was notified, deleted stuff to be "good" again and uploads again, when should he be notified:

Sorry, not sure what we are notifying now? He is good until he hits the quota limit again...

>Should the quota be checked on upload, of async (cron job, can potentially explode for many users)?

This is not so easy - @karlitschek given the performance potential here, I would like input. It seems a cron can explode, and an upload check can slow the rest down...
I would default to a check when a file is to be uploaded.

**Comment by karlitschek** [comment] 2016-02-05 16:57
I'm quote sure we check the quota anyway during upload. So the only thing we additionally need to do is:
if (quote_before_upload>threshold and quote_after_upload<threshold) send_activity and send_notification
Performance impact should be minimal.

**Comment by PVince81** [comment] 2016-05-31 09:59
Closing as duplicate of https://github.com/owncloud/core/issues/6878

Will move the labels there.

**Closed by PVince81** 2016-05-31 09:59 UTC
Labels: blue-ticket, enhancement, feature:new-type
