### ISSUE TITLE
Notifications not shown for files_drop files

### ISSUE THREAD

**Issue by gig13** [owncloud/activity#367] opened 2015-08-20 13:54 UTC
### Steps to reproduce
1. Enable all notifications on
2. Enable files_drop app and create an endpoint
3. Upload a file using files_drop

### Expected behaviour
When uploading a file thorugh files_drop, the activity should show the file as a newly created file in the Activity stream. This should also be included in the email as part of the notifications.

### Actual behaviour
The file is not logged as created in the Acivity log and there is no email notification sent.

### Server configuration
**Operating system**: Ubuntu 14

**Web server:** aapceh 2.4

**Database:**  MySQL 5.5

**PHP version:** 5.5.9-1ubuntu4.11

**ownCloud version:** 8.0.5.2

**Updated from an older ownCloud or fresh install:** Updated

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
See config report
```

### Client configuration
**Browser:** Firefox, IE, Safari

**Operating system:** Windows and Mac

#### Web server error log
```
n/a
```

#### ownCloud log (data/owncloud.log)
```
n/a
```

Config Report available on s3 at https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Factivity%2F367

**Comment by nickvergessen** [comment] 2015-08-24 10:40
Make sure that you have activities for create/change enabled.
Works for me:  `"remote user" created ramdisk.sh`

**Comment by gig13** [comment] 2015-08-24 11:34
@nickvergessen 
Did you test with 8.0.5?

**Comment by LukasReschke** [comment] 2015-08-24 11:35
@gig13 Please use the existing issue. THX.

https://github.com/owncloud/files_drop/issues/61 which shows that https://github.com/owncloud/core/pull/17172 was merged for 8.0.6

**Closed by LukasReschke** 2015-08-24 11:35 UTC
Labels: blue-ticket

**Comment by LukasReschke** [comment] 2015-08-24 11:37
@gig13 Also please try to reproduce issues on your own on the latest release (8.0.6) if the customer does not use the latest release. We shall not waste engineering time on this. THX.

**Comment by gig13** [comment] 2015-08-24 12:00
@LukasReschke @bboule 
Not every user must be forced to upgrade to the latest version contrary to your opinion. I asked a simple question and a simple response would have been adequate. I am testing with 8.0.6 to confirm.

**Comment by LukasReschke** [comment] 2015-08-24 12:03
I'm not talking about the user. I'm talking about support that should try at least in advance to reduce the workload of devs.

**Comment by LukasReschke** [comment] 2015-08-24 12:05
Otherwise we're left with 10000 issues that are filed by users that have not updated their instance while they are fixed in the latest minor release. Yes, bugs might also exist in the latest minor release but if they are fixed there then they should not get filed or at least filed with "it works in $version".

**Comment by gig13** [comment] 2015-08-24 14:29
Works as expected with 8.0.6 -- asking customer to upgrade again, after just upgrading one month ago.

**Comment by nickvergessen** [comment] 2015-08-24 14:32
> Works as expected with 8.0.6 -- asking customer to upgrade again, after just upgrading one month ago.

@gig13 welcome to software usage. Updates are released often, but minor updates (8.0.x to 8.0.x+1) should be somewhat quick
