### ISSUE TITLE
"Favorites" and "All" are showing same content

### ISSUE THREAD

**Issue by plabong** [owncloud/activity#436] opened 2015-11-22 20:33 UTC
### Steps to reproduce
1. Start Activity App
2. Click on "all Activities"
3. Click on "Favorites"

### Expected behaviour
different content should be shown

### Actual behaviour
identical content shown

### Server configuration
**Operating system**:
Debian GNU/Linux 8.2

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (i686)

**PHP version:**
PHP 5.6.14-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
8.2.1.

**Updated from an older ownCloud or fresh install:**
updated admin page updater

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - files: 1.2.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - updater: 0.6

**The content of config/config.php:**
<?php
$CONFIG = array (
  'datadirectory' => '/mnt/nfs/oc81-data',
  'dbhost' => 'localhost',
  'dbname' => 'oc81',
  'dbpassword' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbtype' => 'mysql',
  'dbuser' => 'xxx',
  'default_language' => 'de',
  'forcessl' => true,
  'installed' => true,
  'installedat' => '1337003776.401',
  'instanceid' => 'xxx',
  'lastupdatedat' => '1337004166.2597',
  'logdateformat' => 'Y-m-d H:i:s',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Berlin',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'overwrite.cli.url' => 'https://www.example.com/owncloud',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'share_folder' => '/Shared',
  'theme' => 'example.com',
  'trusted_domains' => array ( 0 => 'www.example.com' ),
  'updatechecker' => false,
  'version' => '8.2.1.4',
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 42.0

**Operating system:**
Windows 7 Pro 64

#### Web server error log
-- nothing while "activity" app active --

#### ownCloud log (data/owncloud.log)
-- nothing while "activity" app active --

#### Browser log
-- nothing --

**Comment by karlitschek** [comment] 2015-11-22 23:47
@PVince81

**Comment by nickvergessen** [comment] 2015-11-23 09:32
We should hide the "favorites" depending on the settings, if you only display favorites in all, it makes no sense to have the filter again, right.

**Comment by nickvergessen** [comment] 2015-11-23 14:21
Actually this seems to all work as intended as none of that is the same:
- `all` contains all activities (file related once are stripped down to favorites)
- `favorites` contains all file related activity (stripped down to favorites)
- `files` contains all file related activity

So the reason why all and favorite seem to be the same for you is, that you don't have share activity entries at the moment.

Closing as such

**Closed by nickvergessen** 2015-11-23 14:21 UTC
Labels: bug, feature:stream, sev4-low
