### ISSUE TITLE
Download of a shared link is broken when activity is enabled

### ISSUE THREAD

**Issue by caco3** [owncloud/activity#435] opened 2015-11-22 20:05 UTC
When I share a file as a link, a user can successfully see its preview.
How ever when he wants to download it, he gets a Server Error (Error 500).

The log shows the following:

```Exception: {"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"public_shared_file_downloaded\", \"[\\\"\\\\\\\/test.txt\\\"]\", \"\", \"[]\", \"\\\/test.txt\", \"\", null, \"***\", 1448222242, 30, \"public_links\", \"\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","Code":0,"Trace":"#0 \/home\/***\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/***\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/home\/***\/www\/owncloud\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/home\/***\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\n#4 \/home\/***\/www\/owncloud\/lib\/private\/db\/querybuilder\/querybuilder.php(121): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 \/home\/***\/www\/owncloud\/apps\/activity\/lib\/data.php(126): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 \/home\/***\/www\/owncloud\/apps\/activity\/lib\/consumer.php(74): OCA\\Activity\\Data->send(Object(OC\\Activity\\Event))\n#7 \/home\/***\/www\/owncloud\/lib\/private\/activitymanager.php(188): OCA\\Activity\\Consumer->receive(Object(OC\\Activity\\Event))\n#8 \/home\/***\/www\/owncloud\/lib\/private\/activitymanager.php(215): OC\\ActivityManager->publish(Object(OC\\Activity\\Event))\n#9 \/home\/***\/www\/owncloud\/apps\/files_sharing\/lib\/controllers\/sharecontroller.php(288): OC\\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '\/test.txt', '', 'g***', 'public_links', 30)\n#10 [internal function]: OCA\\Files_Sharing\\Controllers\\ShareController->downloadShare('WBLuiOanKfjQaYE', NULL, '', '')\n#11 \/home\/***\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#12 \/home\/***\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#13 \/home\/***\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#14 \/home\/***\/www\/owncloud\/lib\/public\/appframework\/app.php(134): OC\\AppFramework\\App::main('ShareController', 'downloadShare', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#15 \/home\/***\/www\/owncloud\/core\/routes.php(124): OCP\\AppFramework\\App->dispatch('ShareController', 'downloadShare')\n#16 [internal function]: OC\\Route\\Router->{closure}(Array)\n#17 \/home\/***\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func(Object(Closure), Array)\n#18 \/home\/***\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/s\/WBLuiOanKfjQ...')\n#19 \/home\/***\/www\/owncloud\/index.php(39): OC::handleRequest()\n#20 {main}","File":"\/home\/***\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":71} ```

When I disable the Activity app, it works correctly!

I run 8.2.1, but it also was broken with older versions.

**Comment by karlitschek** [comment] 2015-11-22 23:47
@nickvergessen

**Comment by nickvergessen** [comment] 2015-11-23 09:35
Duplicate of https://github.com/owncloud/activity/issues/419#issuecomment-149830559

---

You didn't delete the old files and just uploaded the new files into the existing folder.

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Closed by nickvergessen** 2015-11-23 09:35 UTC
Labels: 8.2.1, bug, p2-high

**Comment by caco3** [comment] 2015-11-26 18:53
You are right, sry
Because the update most of the time fails, I started to simply overwrite the installation.
