### ISSUE TITLE
activity app don't show activities

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/activity#185] opened 2014-12-08 13:10 UTC
When I go to the activities, I don't get any information. It loads the whole time but I don't get any error message or information. I waited for half an hour but it always only load. I have this problem in all activities expect for "Activities by others", there I have this message: "You will see a list of events here when you start to use your owncloud.".

In the owncloud log file I only get this error (I currently have debug mode enabled, it's a test machine):

```
{"reqId":"547c63146ad99","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2014-12-01T13:46:12+01:00","method":"GET","url":"\/index.php\/apps\/activity\/ajax\/fetch.php?filter=self&page=1"}
```

In ownCloud 6 this didn't happen. I'm currently using a fresh installation.

### Server configuration
**Operating system**:
Red Hat Enterprise Linux Server release 7.0 (Maipo)

**Web server:**
Apache/2.4.6 (Red Hat)

**Database:**
mysql  Ver 15.1 Distrib 5.5.40-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 5.4.16

**ownCloud version:** (see ownCloud admin page)
7.0.3 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

### Client configuration
**Browser:**
- Firefox 33.0
- Google Chrome 39.0.2171.65 (64-bit)
- Opera 12.16

**Operating system:**
Ubuntu 14.04 LTS

### Network log & console errors
S3-ownCloud/Shared/owncloud/support/github-issues/activity/185

@MorrisJobke 

00002191

**Comment by nickvergessen** [comment] 2015-01-05 08:31
@michaelstingl I'm almost clueless here.
Can you try the RSS feature, whether that works for you, so we know whether its JS related or LDAP/User/Whatever related?

**Comment by cdamken** [comment] 2015-01-05 10:43
Here is the config.php:

```
<?php
$CONFIG = array (
  'appstoreenabled' => false,
  'has_internet_connection' => false,
  'supportedDatabases' => 
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'instanceid' => 'XXXXX',
  'passwordsalt' => 'XXXXX',
  'trusted_domains' => 
  array (
    0 => 'polyboxt01.ethz.ch',
  ),
  'datadirectory' => '/mnt/XXXXXX/data',
  'overwrite.cli.url' => 'https://XXXXXX',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'ownCloudDB1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXX',
  'dbpassword' => 'XXXX',
  'installed' => true,
  'license-key' => 'XXXXXXX',
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'theme' => 'XXXXXX',
  'enable_avatars' => false,
  'logtimezone' => 'XXXXXX',
  'loglevel' => '0',
  'trashbin_retention_obligation' => 6,
  'maintenance' => false,
  'secret' => 'XXXXX',
);
```

**Comment by nickvergessen** [comment] 2015-01-19 11:33
Closing until further information is given.

**Comment by cdamken** [comment] 2015-01-29 18:45
yes, the error is still here in oC 7.0.4. 

@nickvergessen What kind of information do you need?

**Comment by michaelstingl** [comment] 2015-01-29 18:47
@cdamken check my SF comment ;-)

**Comment by nickvergessen** [comment] 2015-01-29 21:48
Duplicate of https://github.com/owncloud/core/issues/13702
Since this is not specific to the activity app, it should be discussed in the core.

**Closed by nickvergessen** 2015-01-29 21:48 UTC
Labels: blue-ticket, needs info

**Comment by michaelstingl** [comment] 2015-04-15 09:49
Customer wrote:

> I now found out that the problem is on the ownCloud software and not on the php version or on the RHEL version.

> When I have a big activity I'm able to see the activity log and there is information filled in. When I have no activity or just not much, the activity loads to infinity and beyond.

**Comment by nickvergessen** [comment] 2015-04-15 09:52
Well that is just symptom not the root cause. If you scroll all the way down it would still have the problem. Anyway, updating should solve it, once we released
