### ISSUE TITLE
Sharing activity with deleted user

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#314] opened 2015-06-27 09:01 UTC
When there was sharing activity with someone in the past, and that person got their account deleted: Should we still show sharing activity with that person, or not?

It just confused me stumbling over this, and I would have expected it not to show since the user does not exist anymore. (At least the activity should be marked as hidden in case the user is restored, or whatnot.) @nickvergessen @owncloud/designers

**Comment by nickvergessen** [comment] 2015-06-27 09:24
Well the problem is that the current system does not allow easy detection of such activities. Also it might be useful to see what items you shared with someone, in terms of which information has been leaked.

**Comment by nickvergessen** [comment] 2015-10-13 15:25
won't fix as per above

**Closed by nickvergessen** 2015-10-13 15:25 UTC
Labels: question
