### ISSUE TITLE
adding a public link to own owncloud does not generate activity entry on the receiver side

### ISSUE THREAD

**Issue by individual-it** [owncloud/activity#800] opened 2019-10-24 11:24 UTC
### Steps to reproduce
1. from server1 create a public link
2. add the public link to the owncloud on server2
3. check the activity on server2

### Expected behaviour
according to the test-plan there should be an activity
`Receive a file/folder via link adding to your owncloud`

### Actual behaviour
no activity is shown

**Comment by davitol** [comment] 2019-10-24 11:35
It was spotted here: https://github.com/owncloud/activity/issues/623#issuecomment-403460450

But I feel OK about having an issue opened separately

**Comment by phil-davis** [comment] 2021-12-17 04:14
Added to QA Test Automation backlog.

Whoever looks into this please:
- confirm if the issue is fixed or not
- confirm if there is an automated test case
- if no automated test case, then add one

**Comment by kiranparajuli589** [comment] 2022-10-17 11:06
The issue is still there. I'll add an automated test for this.

**Comment by kiranparajuli589** [comment] 2022-10-19 10:39
QA Todo:
- [ ] API acceptance test: https://github.com/owncloud/activity/pull/1140
- [ ] WebUI acceptance test (@grgprarup)

**Comment by grgprarup** [comment] 2022-11-09 05:32
API acceptance test and WebUI acceptance test are added for `adding a public link to owncloud`. Works have been finished for now. So closing this issue.

**Closed by grgprarup** 2022-11-09 05:32 UTC
Labels: bug, QA, QA-Team
